name: Deploy Bicep file

env:
    rg: iacbicep

on:
    workflow_dispatch:
    workflow_run:
      workflows: [Validate Template]
      types:
        completed

jobs:
    deploy:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v4
      - name: Login to Azure
        uses: azure/login@v2.2.0
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Deploy Bicep File
        uses: azure/cli@v2.1.0
        with:
          inlineScript: |
            az deployment group create \
            --resource-group ${{ env.rg }} \
            --template-file main.bicep