name: Validate Template

env:
    rg: iacbicep
    rg-location: northeurope

on:
    pull_request:
        branches: ["main"]
        
    workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
    validate-template:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Login to Azure
              uses: azure/login@v2.2.0
              with:
                client-id: ${{ secrets.CLIENT_ID }}
                tenant-id: ${{ secrets.TENANT_ID }}
                subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
            
            - name: Create resource group
              uses: azure/cli@v2.1.0
              with:
                inlineScript: |
                    az group create \
                    --resource-group ${{ env.rg }} \
                    --location ${{ env.rg-location }}

            - name: Validate Bicep template
              uses: azure/cli@v2.1.0
              with:
                inlineScript: |
                    az deployment group validate \
                    --resource-group ${{ env.rg }} \
                    --template-file main.bicep